[deps]
AstroForceModels = "077569d7-e100-45f3-83e3-c646e23345bd"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SatelliteToolboxGravityModels = "bd9e9728-6f7b-4d28-9e50-c765cb1b7c8c"
SatelliteToolboxTransformations = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"
SpaceIndices = "5a540a4e-639f-452a-b107-23ea09ed4d36"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[sources]
AstroForceModels = {path = ".."}